# Generated by Django 4.1.7 on 2023-03-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_record_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
